[changelog]
trim = true

header = """
# Changelog

All notable changes to this project will be documented in this file.
This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""

body = """
{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
    ## [Unreleased]
{% endif -%}
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}

"""

footer = """
## [0.0.1] - 2023-12-22

### Features

- Add release-plz for automated release
- Robot model parsing
- Add legacy path-planning server skeleton
- Add startup code
- Movement executor

### Refactor

- Update terminology
- Robot-model adapter
- Move from Vec to HashMap where possible
"""
