name: Check conventional commits

on: [push]

jobs:
  cog_check_job:
    name: check conventional commit compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install cocogitto
        run: cargo install cocogitto
        
      - name: Conventional commit check
        run: |
          cog check v0.0.3.. --ignore-merge-commits

