name: Update release PR
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'main') }}
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install Git Cliff
        run: cargo install git-cliff
        
      - name: Bump version
        id: bump
        run: |
          BUMPED_VERSION=$(git cliff --unreleased --bump --context | jq -r .[0].version)
          echo "Bumped version: $BUMPED_VERSION"
          echo "bumped_version=$BUMPED_VERSION" >> "$GITHUB_OUTPUT"
          
      - name: update
        run: |
          git cliff --bump > CHANGELOG.md
          echo ------------------------------
          cat CHANGELOG.md
          echo ------------------------------
        
      - uses: peter-evans/create-pull-request@v6
        with:
          add-paths: CHANGELOG.md
          title: "chore: release ${{ steps.bump.outputs.bumped_version }}"
          commit-message: "chore: release ${{ steps.bump.outputs.bumped_version }}"
          branch: "release/${{ steps.bump.outputs.bumped_version }}"
        
